#
# IRIX 6.2
#    To use fltk-config, make sure the fltk directory is in your PATH, eg:
#    set path = ( $path /usr/local/src/fltk-1.1.3 )
#
CC     = CC
CFLAGS = -g -fullwarn -I.
FLTKDIR=/usr/local/src/fltk-1.1.7
FLTKLIBS = -L$(FLTKDIR)/lib -lfltk -L/usr/X11R6/lib -lX11 -lm
REZCOMMAND = @echo

# FLTK-CONFIG
# FLTKLIBS=$(shell fltk-config --ldflags)
